[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-58FB0025961
monitor_port = /dev/cu.usbserial-58FB0025961
lib_deps =
  m5stack/M5Unified@^0.2.14
  z3t0/IRremote@^4.4.1
build_flags =
  -D DISABLE_CODE_FOR_RECEIVER
  -D SEND_PWM_BY_TIMER
